// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/edanko/launches-api/internal/adapters/ent/kind"
	"github.com/edanko/launches-api/internal/adapters/ent/launch"
	"github.com/edanko/launches-api/internal/adapters/ent/order"
	"github.com/edanko/launches-api/internal/adapters/ent/schema"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	kindMixin := schema.Kind{}.Mixin()
	kindMixinFields0 := kindMixin[0].Fields()
	_ = kindMixinFields0
	kindMixinFields1 := kindMixin[1].Fields()
	_ = kindMixinFields1
	kindFields := schema.Kind{}.Fields()
	_ = kindFields
	// kindDescCreatedAt is the schema descriptor for created_at field.
	kindDescCreatedAt := kindMixinFields1[0].Descriptor()
	// kind.DefaultCreatedAt holds the default value on creation for the created_at field.
	kind.DefaultCreatedAt = kindDescCreatedAt.Default.(func() time.Time)
	// kindDescUpdatedAt is the schema descriptor for updated_at field.
	kindDescUpdatedAt := kindMixinFields1[1].Descriptor()
	// kind.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	kind.DefaultUpdatedAt = kindDescUpdatedAt.Default.(func() time.Time)
	// kind.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	kind.UpdateDefaultUpdatedAt = kindDescUpdatedAt.UpdateDefault.(func() time.Time)
	// kindDescName is the schema descriptor for name field.
	kindDescName := kindFields[0].Descriptor()
	// kind.NameValidator is a validator for the "name" field. It is called by the builders before save.
	kind.NameValidator = kindDescName.Validators[0].(func(string) error)
	// kindDescID is the schema descriptor for id field.
	kindDescID := kindMixinFields0[0].Descriptor()
	// kind.DefaultID holds the default value on creation for the id field.
	kind.DefaultID = kindDescID.Default.(func() uuid.UUID)
	launchMixin := schema.Launch{}.Mixin()
	launchMixinFields0 := launchMixin[0].Fields()
	_ = launchMixinFields0
	launchMixinFields1 := launchMixin[1].Fields()
	_ = launchMixinFields1
	launchFields := schema.Launch{}.Fields()
	_ = launchFields
	// launchDescCreatedAt is the schema descriptor for created_at field.
	launchDescCreatedAt := launchMixinFields1[0].Descriptor()
	// launch.DefaultCreatedAt holds the default value on creation for the created_at field.
	launch.DefaultCreatedAt = launchDescCreatedAt.Default.(func() time.Time)
	// launchDescUpdatedAt is the schema descriptor for updated_at field.
	launchDescUpdatedAt := launchMixinFields1[1].Descriptor()
	// launch.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	launch.DefaultUpdatedAt = launchDescUpdatedAt.Default.(func() time.Time)
	// launch.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	launch.UpdateDefaultUpdatedAt = launchDescUpdatedAt.UpdateDefault.(func() time.Time)
	// launchDescReason is the schema descriptor for reason field.
	launchDescReason := launchFields[1].Descriptor()
	// launch.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	launch.ReasonValidator = launchDescReason.Validators[0].(func(string) error)
	// launchDescApplicant is the schema descriptor for applicant field.
	launchDescApplicant := launchFields[4].Descriptor()
	// launch.ApplicantValidator is a validator for the "applicant" field. It is called by the builders before save.
	launch.ApplicantValidator = launchDescApplicant.Validators[0].(func(string) error)
	// launchDescID is the schema descriptor for id field.
	launchDescID := launchMixinFields0[0].Descriptor()
	// launch.DefaultID holds the default value on creation for the id field.
	launch.DefaultID = launchDescID.Default.(func() uuid.UUID)
	orderMixin := schema.Order{}.Mixin()
	orderMixinFields0 := orderMixin[0].Fields()
	_ = orderMixinFields0
	orderMixinFields1 := orderMixin[1].Fields()
	_ = orderMixinFields1
	orderFields := schema.Order{}.Fields()
	_ = orderFields
	// orderDescCreatedAt is the schema descriptor for created_at field.
	orderDescCreatedAt := orderMixinFields1[0].Descriptor()
	// order.DefaultCreatedAt holds the default value on creation for the created_at field.
	order.DefaultCreatedAt = orderDescCreatedAt.Default.(func() time.Time)
	// orderDescUpdatedAt is the schema descriptor for updated_at field.
	orderDescUpdatedAt := orderMixinFields1[1].Descriptor()
	// order.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	order.DefaultUpdatedAt = orderDescUpdatedAt.Default.(func() time.Time)
	// order.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	order.UpdateDefaultUpdatedAt = orderDescUpdatedAt.UpdateDefault.(func() time.Time)
	// orderDescName is the schema descriptor for name field.
	orderDescName := orderFields[0].Descriptor()
	// order.NameValidator is a validator for the "name" field. It is called by the builders before save.
	order.NameValidator = orderDescName.Validators[0].(func(string) error)
	// orderDescID is the schema descriptor for id field.
	orderDescID := orderMixinFields0[0].Descriptor()
	// order.DefaultID holds the default value on creation for the id field.
	order.DefaultID = orderDescID.Default.(func() uuid.UUID)
}
