// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Kind is the predicate function for kind builders.
type Kind func(*sql.Selector)

// Launch is the predicate function for launch builders.
type Launch func(*sql.Selector)

// Order is the predicate function for order builders.
type Order func(*sql.Selector)
